koji_config: brew
redis_url: redis://localhost:6379
registries:
  quay:
    public_url: https://quay.io/
    datasource: direct
    repositories:
      - gmanka/fish
      - gmanka/rigsofrods
      - gmanka/brightnessctl
      - gmanka/gh
      - gmanka/codex
      - gmanka/gitui
      - gmanka/photoshop2021
      - gmanka/photoshop2022
      - gmanka/photoshop2023
      - gmanka/handyfox
      - gmanka/firefox-systemconfig
indexes:
  latest:
    output: pages/index/static
    registry: quay
    architecture_expand: ['']
    tag: latest
    extract_icons: false
