- name: photoshop2021
  id: com.adobe.photoshop2021
  arch: x86_64
- name: photoshop2022
  id: com.adobe.photoshop2022
  arch: x86_64
- name: photoshop2023
  id: com.adobe.photoshop2023
  arch: x86_64
- name: gh
  id: com.github.cli
- name: codex
  id: com.openai.codex
- name: gitui
  id: io.github.gitui_org.gitui
- name: brightnessctl
  id: io.github.hummer12007.brightnessctl
- name: handyfox
  id: io.github.pocketblue.handyfox
  repo_url: https://github.com/pocketblue/handyfox
- name: fish
  id: org.freedesktop.Sdk.Extension.fish
  type: runtime
  branch: '25.08'
- name: firefox-systemconfig
  id: org.mozilla.firefox.systemconfig
  type: runtime
  branch: stable
  repo_url: https://github.com/pocketblue/firefox-systemconfig
- name: rigsofrods
  id: org.rigsofrods.RigsOfRods
